### ISSUE TITLE
can't assign units in ruby 2.0

### ISSUE THREAD

**Issue by jpaas** [sdague/temperature.rb#3]
In Ruby 2.0, it appears you can no longer assign units to a number because they are considered immutable.

If I do
    temperature = 2.0
    temperature.units = 'C'

I'll get
    RuntimeError (can't modify frozen Float)

**Comment by muloka** [comment]
👍

**Comment by sdague** [comment]
I'm not maintaining this project any more, if anyone else wants to take this over, that would be cool
